/**********************************************************************
* File: Main_BIOS.c
* Devices: TMS320F2803x
* Author: David M. Alter, Texas Instruments Inc.
* History:
*   07/08/09 - original (D. Alter)
**********************************************************************/
#include "F28035_example.h"				// Main include file

//--- Global Variables

//--- Global functions
void SysParamDefault(); 

/**********************************************************************
* Function: main()
*
* Description: Main function for F2803x example.
**********************************************************************/
void main(void)
{
//--- CPU Initialization
	InitSysCtrl();						// Initialize the CPU
	InitPieCtrl();						// Initialize and enable the PIE
	InitWatchdog();						// Initialize the Watchdog Timer
	InitGpio();							// Initialize the shared GPIO pins
   
   
	Init_Scia(TEST_COMM_BAUDRATE, MODE_INT);
 
#ifdef EXAMPLE_FLASH					// EXAMPLE_FLASH, if defined, is in CCS project options

//--- Copy all Flash sections that need to run from RAM (use memcpy() from RTS library)

// Section secureRamFuncs contains user defined code that runs from CSM secured RAM
	memcpy(&secureRamFuncs_runstart, &secureRamFuncs_loadstart, (Uint32)&secureRamFuncs_loadsize);

//--- Initialize the Flash and OTP
	InitFlash();						// Initialize the Flash

#endif

//--- Peripheral Initialization

//    GPIO25_Xint_Init();

	AdcRegs.ADCCTL1.bit.RESET = 1;		// Reset the ADC
	// Please note that for the delay function below to operate correctly the
    // CPU_RATE define statement in the DSP2803x_Examples.h file must
    // contain the correct CPU clock period in nanoseconds.
    EALLOW;
    AdcRegs.ADCCTL1.bit.ADCBGPWD  = 1;      // Power ADC BG
    AdcRegs.ADCCTL1.bit.ADCREFPWD = 1;      // Power reference
    AdcRegs.ADCCTL1.bit.ADCPWDN   = 1;      // Power ADC
    AdcRegs.ADCCTL1.bit.ADCENABLE = 1;      // Enable ADC
    AdcRegs.ADCCTL1.bit.ADCREFSEL = 1;      // Select interal BG
    EDIS;

	AdcOffsetSelfCal();

	InitAdc();							// Initialize the ADC
	InitEPwm();							// Initialize the PWM
	InitECap();							// Initialize the Capture units
	InitECan();							// Initialize the ECan.
	InitECana();						// Initialize the ECana.
	EEPROMParamDefault();
    SysParamDefault(); 
	
//	ReadEnergyOutput_PowerUp();
//--- Enable interrupts
	SetDBGIER(IER | 0x6000);							// Enable everything in IER, plus TINT2 and DLOGINT
	*(volatile unsigned int *)0x00000C14 |= 0x0C00;		// Set TIMER2 FREE=SOFT=1
    // DSP/BIOS will enable global interrupts (INTM and DBGM)
} // end of main()



/**********************************************************************
* Function: UserInit()
*
* Description: This is the user initialization file to be specified in
* the DSP/BIOS configuration file, System - Global Settings.
**********************************************************************/
void UserInit(void)
{
#ifdef EXAMPLE_FLASH					// EXAMPLE_FLASH, if defined, is in CCS project options

// Section .trcdata is generated by DSP/BIOS.
// It must be copied from its load to its run address BEFORE main().
	memcpy(&trcdata_runstart, &trcdata_loadstart, (Uint32)&trcdata_loadsize);

#endif

} // end of UserInit()



/**********************************************************************
* Function: SysParamDefault(void)
*
* Description: This is the user initialization
*  - Global Settings.
**********************************************************************/

void SysParamDefault(void)
{
	Uint8 u8temp = 0;
 	SCR_Bypass_Disable();
 	SCR_INV_Disable();

	ADGain.iq20VGrid = VGridMeasureGain;
	ADGain.iq20TempAmb = TempAmbMeasureGain;

	SafetyReg.i32FreGrid_HiLimit = FreGridHiLimit;
	SafetyReg.i32FreGrid_LowLimit = FreGridLowLimit;
	SafetyReg.u16FreGrid_ProtectionTime = FreGridProtectionTime;

	u8temp = ProtectionSet0 + ProtectionSet1 * 2;
	if (u8temp == 0x00)
	{
		SafetyReg.iq20VGrid_HiLimit = VGridHi1Limit;
		SafetyReg.iq20VGrid_LowLimit = VGridLow1Limit;
	}
	else if (u8temp == 0x01)
	{
		SafetyReg.iq20VGrid_HiLimit = VGridHi2Limit;
		SafetyReg.iq20VGrid_LowLimit = VGridLow2Limit;
	}
	else
	{
		SafetyReg.iq20VGrid_HiLimit = VGridHi2Limit;
		SafetyReg.iq20VGrid_LowLimit = VGridLow2Limit;
	}

	SafetyReg.iq20VGrid_HiLimitBack = SafetyReg.iq20VGrid_HiLimit - _IQ(5);
	SafetyReg.iq20VGrid_LowLimitBack = SafetyReg.iq20VGrid_LowLimit + _IQ(5);
	
	SafetyReg.u16VGrid_ProtectionTime = VGridProtectionTime;
	SafetyReg.u16TempAmb_HiLimit = TempAmbHiLimit;
	SafetyReg.u16TempAmb_ProtectionTime = TempProtecitonTime;

	ADChannelOffset.iq20VGrid = 0;
	ADChannelOffset.iq20VOut = 0;
	ADChannelOffset.iq20IGrid = 0;
	ADChannelOffset.iq20TempAmb = 0;

	ADGain.iq20VGrid = VGridMeasureGain;
	ADGain.iq20VOut = VOutMeasureGain;
	ADGain.iq20IGrid = IGridMeasureGain;
	ADGain.iq20TempAmb = TempAmbMeasureGain;

	ADCalibration.iq20VGrid = 1;
	ADCalibration.iq20VOut = 1;
	ADCalibration.iq20IGrid = 1;
	ADCalibration.iq20TempAmb = 1;

	AD_Acc.iq10TempAmb = 0;
	AD_Acc.iq2VGrid_RMS = 0;
	AD_Acc.iq10GridFreq = 0;
	AD_Acc.i16Counter = 0;
	AD_Acc.iq10IGrid_RMS = 0;
	AD_Acc.iq2VOut_RMS = 0;
	AD_Acc.iq20VGrid_ave = 0;
	AD_Acc.iq20VOut_ave = 0;

	AD_Sum.iq10TempAmb = 0;
	AD_Sum.iq2VGrid_RMS = 0;
	AD_Sum.iq10GridFreq = 0;
	AD_Sum.i16Counter = 0;
	AD_Sum.iq10IGrid_RMS = 0;
	AD_Sum.iq2VOut_RMS = 0;
	AD_Sum.iq20VGrid_ave = 0;
	AD_Sum.iq20VOut_ave = 0;

	Calc_Result.iq20TempAmb = 0;
	Calc_Result.iq20VGrid_RMS = 0;
	Calc_Result.iq20GridFreq = 0;
	Calc_Result.i16Counter = 0;
	Calc_Result.iq20IGrid_RMS = 0;
	Calc_Result.iq20VGrid_ave = 0;
	Calc_Result.iq20VOut_RMS = 0;
	Calc_Result.iq20VOut_ave = 0;

	g_SysFaultMessage.Word.byte0 = 0;
	g_SysFaultMessage.Word.byte1 = 0;

	g_StateCheck.Word.byte0 = 0;
	g_StateCheck.Word.byte1 = 0;
	g_StateCheck.bit.AD_initial  = 1;

	g_SysWarningMessage.Word.byte0 = 0;
	g_SysWarningMessage.Word.byte1 = 0;

	//ECan
	Ecan_ModuleData.Check = 0;

	Ecan_ModuleData.Alert.Byte.Alert= 0;
	Ecan_ModuleData.Fault.Byte.Fault1 = 0;
	Ecan_ModuleData.Fault.Byte.Fault2 = 0;

	Ecan_ModuleData.u16IGrid_rms = 0;
	Ecan_ModuleData.u16VGrid_rms = 0;

	Ecan_ModuleData.u16VGrid_Freq = 0;
	Ecan_ModuleData.u16Temperature = 0;
	Ecan_ModuleData.u16VOut_rms = 0;

	Ecan_ModuleData.u16RunTimeu16Hour_H = 0;
	Ecan_ModuleData.u16RunTimeu16Hour_L = 0;

	 Ecan_SytemREVISED.u16VGrid_rms = 0;
	 Ecan_SytemREVISED.u16IGrid_rms = 0;
	 Ecan_SytemREVISED.u16Temperature = 0;
	 Ecan_SytemREVISED.u16VOut_rms = 0;
	 //ECan upper computer order
	 Ecan_SysParaCalibration.rsvr0 = 0;
	 Ecan_SysParaCalibration.Defaluts = 0xFFFF;
	 Ecan_SysParaCalibration.Output_Enable = 0;
	 Ecan_SysParaCalibration.rsvr1 = 0;

	 EcanP2A_Tx.P2AMail_id.all = 0xC0000007;
	 EcanP2A_Tx.P2AMail_data.DWord.CANH_Bytes = 0x00000000;
	 EcanP2A_Tx.P2AMail_data.DWord.CANL_Bytes = 0x00000000;

	 Ecan_Error.u8Upload_Trans_Error = 0;
	 Ecan_Error.u8Broadcast_Trans_Error = 0;

	 RunningTime.u16Hour_H = 0;
	 RunningTime.u16Hour_L = 0;
	 RunningTime.u16Minute = 0;
	 RunningTime.u16Second = 0;
	 RunningTime.u16OverFlow = 0;
	 RunningTime.u16TimeCheck = 0;
}    

/**********************************************************************
* FUNCION :  SEM post  when periodic   timerBase of 2ms   is ready
* PURPOSE :  SEM post  for  state changed
* INPUT :
*        void
* RETURN :
*        void
* CALLS:
*        void
*
* CALLED BY:  DSP/BIOS kernel 2ms periodic  call 
* 
**********************************************************************/
void TimeBase2msPRD(void)
{  // static Uint16 LedPrd2msCount=0;
   SEM_post(&TimeBase2msReady);
   FanCntl();
}

/**********************************************************************
* FUNCION :  SEM post  when  periodic  timerBase of 10ms  is ready
* PURPOSE :  SEM post  for  MPPT or anti islanding detection
* INPUT :
*        void
* RETURN :
*        void
* CALLS:
*        void
*
* CALLED BY:  DSP/BIOS kernel 10ms periodic  call 
* PRD_TimeBase500ms
**********************************************************************/
void TimeBase500msPRD(void)
{
	SEM_post(&SEM_TimeBase500ms);     
} // end of TimerBase10msPRD()


/*Modified by Shen Yuan -2011.11.2*/
/**********************************************************************
* FUNCION :  
* PURPOSE :
* INPUT :
*        void
* RETURN :
*        void
* CALLS:
*        void
*
* CALLED BY:  DSP/BIOS kernel
**********************************************************************/
void TimeBase20msPRD(void)
{
	DitherEliminate();
} // end of TimerBase20msPRD()

//--- end of file -----------------------------------------------------



